### ISSUE TITLE
inform qubes of layout changes

### ISSUE THREAD

**Issue by o-** [SietsevanderMolen/i3-qubes#3]
On screen geometry change we should call:
    qubes-monitor-layout-notify
otherwise parts of appvm windows remain unclickable.

Not sure if we should teach i3 to call this script on layout change, add some external method, or just explain in the README to call it manually. What do you think?

**Comment by SietsevanderMolen** [comment]
Hmm, nice find. :-) I've been using i3 in Qubes for a while now and never noticed this. I have no idea where we would call this from i3 itself though, so for now the best and easiest solution is to just add it to the README. We can automate it later when we find out how, agree? Will you add it?

**Comment by SietsevanderMolen** [comment]
Ok, update. I had some time to look into this, and it seems we have https://github.com/QubesOS/qubes-gui-daemon/blob/master/screen-layout-handler/. This means we can just run

```
/usr/libexec/qubes/watch-screen-layout-changes qubes-monitor-layout-notify
```

and that should take care of things. No need to change anything in i3 itself. (although we could have done that in output_change_mode in randr.c)
