### ISSUE TITLE
404 fetching i3-4.8.tar.bz2 in AppVM

### ISSUE THREAD

**Issue by mig5** [SietsevanderMolen/i3-qubes#5]
Hi,

Running the fedpkg command I get a 404 error:

[user@temp-i3 i3-qubes]$ fedpkg --dist f20 local --builddir ~/rpmbuild
Downloading i3-4.8.tar.bz2
###### ################################################################## 100.0%

Could not execute local: Server returned status code 404

Do we have to run these commands on a Fedora 20 template, rather than Fedora23, due to the version in dom0?

Thanks for your work on this.

**Comment by mig5** [comment]
Some more debug info. It seems like it's munging the URL to fetch the tarball somehow. I can't work out how to change this, even if I hardcode the URL in the i3.spec (I'm a Debian person, so the rpm/fedpkg stuff is a bit alien to me)

Cheers

```
[user@temp-i3 i3-qubes]$ fedpkg --verbose --debug --dist f20 local --builddir ~/rpmbuild
Creating repo object from /home/user/i3-qubes
Could not determine the remote name: 'git config --get branch.f20.remote' returned with exit code 1
Falling back to default remote name 'origin'
Downloading i3-4.8.tar.bz2
Full url: http://pkgs.fedoraproject.org/repo/pkgs/i3-qubes/i3-4.8.tar.bz2/md5/4151e8e81fdc78b32a7cb953f67e3bef/i3-4.8.tar.bz2
######################################################################## 100.0%
Could not execute local: Server returned status code 404
Traceback (most recent call last):
  File "/usr/bin/fedpkg", line 16, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/fedpkg/__main__.py", line 69, in main
    sys.exit(client.args.command())
  File "/usr/lib/python2.7/site-packages/pyrpkg/cli.py", line 1161, in local
    builddir=self.args.builddir)
  File "/usr/lib/python2.7/site-packages/pyrpkg/__init__.py", line 2147, in local
    self.sources()
  File "/usr/lib/python2.7/site-packages/pyrpkg/__init__.py", line 1740, in sources
    hashtype=entry.hashtype, branch=self.branch_merge)
  File "/usr/lib/python2.7/site-packages/pyrpkg/lookaside.py", line 174, in download
    raise DownloadError('Server returned status code %d' % status)
pyrpkg.errors.DownloadError: Server returned status code 404
```

**Comment by mig5** [comment]
I found if I set a dummy git config value : 

```
git config --add branch.f20.remote 0
```

then I could proceed through that section.

Then, in addition to these packages (which weren't in your blog post but were in the README): 

```
asciidoc bison doxygen flex libX11-devel libXcursor-devel libxcb-devel libxkbfile-devel pango-devel perl startup-notification-devel xcb-proto xcb-util-cursor-devel xcb-util-devel xcb-util-keysyms-devel xcb-util-wm-devel xmlto yajl-devel

```

I also had to install:

```
libev-devel pcre-devel 'perl(Data::Dumper::Names)' gcc
```

.. to complete the build.

**Comment by SietsevanderMolen** [comment]
Thanks for reporting your experience! Seems like I forgot some stuff. :-) I'll redo and update the blog post/readme as soon as I can.

**Comment by SietsevanderMolen** [comment]
I redid the build system: https://github.com/SietsevanderMolen/i3-qubes/pull/9 This should fix these problems.
