### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by minad** [SietsevanderMolen/i3-qubes#8]
I think fullscreen mode should be forbidden in qubes or only allowed if certain configuration options are set? This is not yet implemented by i3-qubes.

**Comment by SietsevanderMolen** [comment]
Hmm, I need to read up on how this works exactly. Parsing guid.conf seems a bit excessive.

**Comment by minad** [comment]
Maybe we could look at the patches to the other WMs also to be sure not to have missed things.

**Comment by SietsevanderMolen** [comment]
Exactly what I was going to propose. :) bit busy now, but I can look at it during the weekend

**Comment by minad** [comment]
No hurry for now. but in the long term I think it would be great to have it included in qubes. I guess there are many "power users" interested in qubes in combination with tiling WMs. This was also one of the first things I looked into. If I wouldn't have found your repository I probably wouldn't have it installed. And the first minutes using KDE were really a pain in the ass :hankey:

**Comment by minad** [comment]
I've not seen any fullscreen specific patches in the xfce window manager. Do you know how this fullscreen thing is supposed to work?

**Comment by SietsevanderMolen** [comment]
Not at all, I was looking for the same thing. I could make it so that every full screen window honours the borders, but I'd like to have it configurable like it's supposed to be.

**Comment by minad** [comment]
@marmarek Could you tell us more about this fullscreen mode? Where is this done in xfce for example?

**Comment by marmarek** [comment]
There is nothing specific at window manager side. If set using window manager shortcut/menu (so at user discretion, not application) it's ok. By default gui-daemon do not pass such requests from applications (unless appropriate setting is enabled in guid.conf).

**Comment by minad** [comment]
ok thx
